### ISSUE TITLE
Polygon mode packing

### ISSUE THREAD

**Issue by amakaseev** [amakaseev/sprite-sheet-packer#10]
work on algorithm of packing of polygons if you have ideas is begun tell me please.

**Comment by amakaseev** [comment]
now I think to realize algorithm when after sorting according to the size of a polygons to try to add near each top of already added polygon until resulting volume isn't the smallest

**Comment by TheCodez** [comment]
For saving polygons in the plist you also have to use plist format 3

**Comment by amakaseev** [comment]
yes of course
but it not soon :(

**Comment by amakaseev** [comment]
progress: https://www.dropbox.com/s/tf2jmmr0sftpj1g/Screenshot%202016-01-20%2017.03.55.png?dl=0

**Comment by TheCodez** [comment]
Good work. However in the picture you sent there is some overlapping. But for the first working Version it looks really promising.

**Comment by amakaseev** [comment]
> some overlapping

I can not understand because of what the overlap :(
where the error in determining the intersection ...

**Comment by TheCodez** [comment]
Is support for rotation planned?

**Comment by amakaseev** [comment]
I'm not sure that it gives a better result, as is already the result is impressive, and the rotation of the package will increase the time twice :(

**Comment by amakaseev** [comment]
I have about the priorities are:
1) save of polygons to plist
2) stave pvrtc texture
....

**Comment by TheCodez** [comment]
OK a even slower packing wouldn' be good. Maybe Generating on a second thread is something to consider.

**Comment by TheCodez** [comment]
Removing this [line](https://github.com/amakaseev/sprite-sheet-packer/blob/master/SpriteSheetPacker/algorithm/polypack2d.h#L219) gave me 2 seconds speed improvements in a 2000x2000 sheet.

**Comment by amakaseev** [comment]
Thank you, good that you noticed. I will optimize the implementation of the intersections

**Comment by TheCodez** [comment]
Do you think you're able to optimize the packing to about half the current generation time?

**Comment by amakaseev** [comment]
Not at this time, I'm going to remove the re-generation of the atlas if the project has not been modified.

**Comment by amakaseev** [comment]
and now all the forces thrown at PVR format
