### ISSUE TITLE
Support pvr texture format

### ISSUE THREAD

**Issue by amakaseev** [amakaseev/sprite-sheet-packer#12]
https://imgtec.com

**Comment by TheCodez** [comment]
Probably create your own image loader like the webp, doesn't seem that complicated with pvrtexlib:
https://github.com/qtproject/qtimageformats/tree/dev/src/plugins/imageformats/webp

**Comment by amakaseev** [comment]
I thoroughly didn't study this subject yet
but I know that there is a loader

use in cocos2d-x:
PVRTDecompress.h: [PowerVR Software Development Kit](http://downloads.isee.biz/pub/files/tmp/igep-dsp-gst-framework-3_40_00/Graphics_SDK_4_05_00_03/GFX_Linux_SDK/OGLES2/SDKPackage/Tools/Documentation/html/files.html)

**Comment by amakaseev** [comment]
but I didn't see the compress there

**Comment by TheCodez** [comment]
Creating an image Format Plugin and copy that to the qt bins is probably the way to go. Otherwise you have to change all places where image is loaded and saved. Creatig a New image Format loader removes that need.
I gave you an example on how it is implemented for [webp](https://github.com/qtproject/qtimageformats/tree/dev/src/plugins/imageformats/webp).

**Comment by amakaseev** [comment]
Yes, it's a good idea, thank you.

**Comment by TheCodez** [comment]
I could help on that, but pvr currently can't compile on windows

**Comment by amakaseev** [comment]
I do not have access to windows os. I'm done with image format and pixel format, and see that there is a  compiler error

**Comment by TheCodez** [comment]
So image format and pixelformat is now changeable? Btw this is the error I get
![image](https://cloud.githubusercontent.com/assets/4009589/12581234/9b62f292-c435-11e5-9b41-a71411f015ae.png)

**Comment by amakaseev** [comment]
i found in PVRTextureDefines.h
12: //To use the PVRTexLib .dll on Windows, you need to define _WINDLL_IMPORT
> So image format and pixelformat is now changeable?

the following commits I add formats

**Comment by TheCodez** [comment]
Gives me this error 
![image](https://cloud.githubusercontent.com/assets/4009589/12582144/8d284794-c43b-11e5-86f6-17245e32fc08.png)

**Comment by amakaseev** [comment]
if you try to MSVC compiler?
PVRTexLib.lib probably only MSVC?

**Comment by amakaseev** [comment]
or incorrect
win32:contains(QMAKE_HOST.arch, x86_64) {
    LIBS += $$PWD/Windows_x86_64/PVRTexLib.lib
.......

try with out if...
LIBS += $$PWD/Windows_x86_64/PVRTexLib.lib

**Comment by TheCodez** [comment]
No doesnt work either

**Comment by TheCodez** [comment]
The error i get now with mvsc 
![image](https://cloud.githubusercontent.com/assets/4009589/12587697/bebefe5a-c455-11e5-8c15-5be1f95a32e5.png)

**Comment by amakaseev** [comment]
I will try to install visual studio 2013 ...
oh how about I do not know mingw :(

**Comment by amakaseev** [comment]
windows forever with problems :-1:

**Comment by KAMIKAZEUA** [comment]
Just saw you app on cocos2d-x forum. It's really cool! texturepacker(commercial product) gonna die lol)

I don't know if this helps, but CocosBuilder successfully pack's pvr and pvr.ccz files. 
Maybe you can find something useful here: 
https://github.com/KAMIKAZEUA/CocosBuilder/tree/v1.5/CocosBuilder/libs/PVRTexTool
https://github.com/KAMIKAZEUA/CocosBuilder/tree/v1.5/CocosBuilder/libs/Tupac
I never dig so deep to check how it works, I just did a simple fixes and improvements to CocosBuilder. 

> windows forever with problems 👎

Oh yea, I really understand you in that, it's sucks.

**Comment by amakaseev** [comment]
I have understood why compression didn't work there is pvr has to be always square
