### ISSUE TITLE
Pngquant image optimization

### ISSUE THREAD

**Issue by TheCodez** [amakaseev/sprite-sheet-packer#15]
I've already added the pngquant optimizer. I will send a pr it as soon as the optimizer pr is merged. The only thing i don't know yet with pngquant is, what the png opt level slider is for. It should use the slowest generation, so that the the output image quality istn't that much sacrified.Maybe optslider changes the compression of the saved image.

**Comment by amakaseev** [comment]
Done.
I have a few days did not have the opportunity to work on a project :(

**Comment by TheCodez** [comment]
I create a pr in a few minutes.

**Comment by TheCodez** [comment]
Done!

**Comment by TheCodez** [comment]
Maybe add a combobox to properties with lossless, lossy and anly when lossless is selected show PNG opt slider.

**Comment by amakaseev** [comment]
crash: if close publish dialog before optimization finishes work

**Comment by TheCodez** [comment]
Both or just the pngquant? I'll try to fix that

**Comment by amakaseev** [comment]
541: publishStatusDialog->setAttribute(Qt::WA_DeleteOnClose);
after thread is finished:
607: publishStatusDialog->log(QString("Publishing is finished."), Qt::blue);

**Comment by amakaseev** [comment]
Maybe you need to do to optimize png a single progress bar in the status bar? PublishStatusDialog and do not dependent png optimization?
