### ISSUE TITLE
Add save dialog on exit

### ISSUE THREAD

**Issue by TheCodez** [amakaseev/sprite-sheet-packer#17]
When a property is changed display an save or discard dialog when the exit button is clicked.
![image](https://cloud.githubusercontent.com/assets/4009589/12379935/4b64c972-bd65-11e5-9dba-a0bb3058742b.png)

**Comment by amakaseev** [comment]
Oh yes) it's fine

**Comment by TheCodez** [comment]
is there a way to always call a signal whenever any property is changed. It's kinda ugly connecting every property.

**Comment by amakaseev** [comment]
I dont know... only 
connect(ui->trimSpinBox, SIGNAL(valueChanged(int)), this, SLOT(propertiesValueChanged(int)));
for all items
>Well, then i have to do that for all properties that are saved in the project file.

Yes, it is ugly, but I do not know any other way.
