### ISSUE TITLE
Cache atlases

### ISSUE THREAD

**Issue by TheCodez** [amakaseev/sprite-sheet-packer#24]
Cache already created atlases to speedup generation by reusing them.

**Comment by amakaseev** [comment]
:+1:

**Comment by amakaseev** [comment]
(0716e6867d5914c6c3765c48f469ffa0c7e2eb38)[https://github.com/amakaseev/sprite-sheet-packer/commit/0716e6867d5914c6c3765c48f469ffa0c7e2eb38]
