### ISSUE TITLE
Compile error with QT5.21 on mac

### ISSUE THREAD

**Issue by yingnierxiao** [amakaseev/sprite-sheet-packer#31]
![qq20160709-0 2x](https://cloud.githubusercontent.com/assets/3435706/16708413/873c73fc-4625-11e6-9fa8-489c17ac4528.png)

**Comment by amakaseev** [comment]
in what there was a problem?
my help isn't necessary?

**Comment by yingnierxiao** [comment]
this ok close  pvr Compile option

**Comment by sersoong** [comment]
How to close pvr Compile option?
