### ISSUE TITLE
Crashes when ren from command line with project argument (Windows)

### ISSUE THREAD

**Issue by Riva3000** [amakaseev/sprite-sheet-packer#43]
Crashes every time with exit code -1 or -1073741571.
Example project file with 100% repro attached.
The project was created in GUI and when used in GUI, it works fine.

**Comment by Riva3000** [comment]
Having trouble attaching the zip.
So here http://temp.pixellive.net/ExampleProject.zip

**Comment by amakaseev** [comment]
Hi, thanks that noticed an error.
Report what operating system at you, I for you will build the sprite packer.

[fied](https://github.com/amakaseev/sprite-sheet-packer/commit/5df52da5a8732df4e0e61ed7cfbb161ab3a473f2)

**Comment by Riva3000** [comment]
Hello
I use the Sprite Packer on Windows 7 (64bit).
Thanks

**Comment by amakaseev** [comment]
Try this [release](https://github.com/amakaseev/sprite-sheet-packer/releases/tag/1.0.9) plz

**Comment by Riva3000** [comment]
Could you maybe send me just zipped binaries ?
For quick testing that will be faster than installation.

**Comment by amakaseev** [comment]
Please report, the bug is fixed?
