### ISSUE TITLE
Add GNU/Linux support

### ISSUE THREAD

**Issue by NathV** [amakaseev/sprite-sheet-packer#46]
This program only support win32 and mac0SX, can you please add support for GNU/Linux ?

**Comment by amakaseev** [comment]
Can you add support of GNU/Linux?
I unfortunately have no Linux system

**Comment by NathV** [comment]
@amakaseev This is what i do, i will send you my modification soon.

**Comment by amakaseev** [comment]
That's wonderful!

**Comment by NathV** [comment]
Ok, i can work with the app, you can see the changes in the [.diff file](https://pastebin.com/PZu1jyhA).

But you have to copy libPVRTexTool.so to /usr/lib, since this isn't very flexible i will try to create a script that will automatically add the file folder to `LD_LIBRARY_PATH`, as the Qt team advise to do [here](https://doc.qt.io/qt-5/linux-deployment.html#creating-the-application-package) .

I had "Ambiguous overload call to abs" errors so i changed the  `abs` into `std::abs` in PolygonImage.cpp.

I've create a "install/linux/bin" folder.

TODO : 
Add [linuxdeployqt](https://github.com/probonopd/linuxdeployqt).
Create a script to add libPVRTexTool to `LD_LIBRARY_PATH.`
Add updater support.

**Comment by amakaseev** [comment]
Create pull request in which you will be able to make the changes.
When you finish I will make merge in the main repository

**Comment by NathV** [comment]
Do my changes disturb the MacOsX or Windows installation ?

**Comment by amakaseev** [comment]
I have checked for macos - everything very well
you have done good work, thanks!
