### ISSUE TITLE
File extension (*.png) is not add to key

### ISSUE THREAD

**Issue by crazyhappygame** [amakaseev/sprite-sheet-packer#49]
In folder abc_0 there is file 00.png. But key has value <key>abc_0/00</key>. 

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
 <dict>
  <key>frames</key>
  <dict>
   <key>abc_0/00</key>
   <dict>
    <key>aliases</key>
    <array/>
    <key>spriteOffset</key>
    <string>{-1,1}</string>
    <key>spriteSize</key>
    <string>{71,73}</string>
    <key>spriteSourceSize</key>
    <string>{75,98}</string>
    <key>textureRect</key>
    <string>{{85,0},{71,73}}</string>
    <key>textureRotated</key>
    <false/>
   </dict>
```

**Comment by amakaseev** [comment]
<img width="292" alt="screen shot 2017-09-21 at 08 44 30" src="https://user-images.githubusercontent.com/9881001/30680592-33a7d8f2-9ea9-11e7-87a3-452858891f8c.png">

be convinced that the tick of "Trim sprite names" is switched off

**Comment by crazyhappygame** [comment]
OK. From UI it works. How to switch this from command-line?

**Comment by Ronsku** [comment]
Is this still an issue in the CLI? Is this an active project?

**Comment by amakaseev** [comment]
try [this](https://github.com/amakaseev/sprite-sheet-packer/commit/ec6151edf90843b266e86851723a24c6a054c5da)

**Comment by amakaseev** [comment]
> Is this still an issue in the CLI? Is this an active project?
It's work from source but I'm very busy to do new releases
