### ISSUE TITLE
unable to start correctly (0xc000007b)

### ISSUE THREAD

**Issue by shohiebsense** [amakaseev/sprite-sheet-packer#52]
im using windows 10 and after installed, then i got this error.
![2017-09-25 12_58_01-yasuda rei - mirror 01 mirror foobar2000 v1 3 16](https://user-images.githubusercontent.com/9792782/30794289-809f7304-a1f1-11e7-903d-10b7410b2c11.png)

**Comment by NathV** [comment]
Try to run it as administrator and reinstall Microsoft Visual C++ Redistributable Packages.
Check this link too : https://www.drivereasy.com/knowledge/how-to-fix-the-application-is-unable-to-start-correctly-0xc00007b-error/

**Comment by Cabrill** [comment]
![image](https://user-images.githubusercontent.com/2907579/31190283-598fee52-a943-11e7-9740-d80686b17fae.png)
I'm getting the same error, even after following all those steps.  I used DependencyWalker and learned the most likely cause is that the QT*.dll files are for x86, not x64.

**Comment by Riva3000** [comment]
I'm just reporting that I have the same issue. Windows 7 Ultimate 64bit.

@NathV Wouldn't you know which VC redists is the app using ?
I traditionaly have dozens of versions installed (both for x86 and x64) and reinstaling them all blindly would be a major pain.

**Comment by NathV** [comment]
@Riva3000 
I'm not sure, but try with Visual C++ 2013 Redistributable 12.0.21005,
You can also check between line 70 and 119 [here](https://github.com/amakaseev/sprite-sheet-packer/blob/master/install/win/installer.iss)

**Comment by amakaseev** [comment]
Try plz this 32b version https://github.com/amakaseev/sprite-sheet-packer/releases/download/1.0.9/SpriteSheetPacker-Installer.exe

**Comment by amakaseev** [comment]
I seldom work under Windows, but I know that there are a lot of problems with libraries

**Comment by shohiebsense** [comment]
Never mind, i am using visual studio with QT plugin and worked. Guess this could be closed from now.
