### ISSUE TITLE
Cannot build with Qt Creator 4.5.2

### ISSUE THREAD

**Issue by aggsol** [amakaseev/sprite-sheet-packer#55]
I get the following error message:
```
Could not find qmake spec 'default'.
Error while parsing file /home/user/projects/sprite-sheet-packer/sprite-sheet-packer.pro. Giving up.
```

Which Qt Creator Version do you user?

**Comment by amakaseev** [comment]
Sorry, long I didn't answer
My Qt Creator is 4.4.1, Soon I do try 4.5+ version, and report for you.

**Comment by amakaseev** [comment]
<img width="698" alt="screen shot 2018-03-29 at 08 33 49" src="https://user-images.githubusercontent.com/9881001/38071791-fe4d91d4-332b-11e8-821c-ee60bb8acb8f.png">

Compiling very well.

**Comment by aggsol** [comment]
Then there is something else wrong with my installation.

**Comment by piratesephiroth** [comment]
As a note for anyone interested (or myself, if I forget)
We can build SpriteSheet Packer on WIndows using Qt 5.9.8 with the MSVC 2015 32-bit kit.
