### ISSUE TITLE
Optimize PNG

### ISSUE THREAD

**Issue by TheCodez** [amakaseev/sprite-sheet-packer#7]
Why not add a postprocessing step and run [OptiPNG](http://optipng.sourceforge.net/) after generating png. The easiest thing would probably be just running optipng after generating using QProcess.

**Comment by amakaseev** [comment]
yes OptiPNG at me was in plans

**Comment by TheCodez** [comment]
Do you think it's a good idea to run it using a QProcess?

**Comment by amakaseev** [comment]
QProcess run application platform the dependent

**Comment by amakaseev** [comment]
I thought to connect source codes and to start optimization in a QThread

**Comment by TheCodez** [comment]
I looked at the optipng open api, i think the hardest thing is to get the sources into qt.

**Comment by TheCodez** [comment]
If you could help me on that part, then I would do the implementation.

**Comment by amakaseev** [comment]
yes I will try to connect source codes tomorrow

**Comment by amakaseev** [comment]
now is including optipng sources

**Comment by amakaseev** [comment]
compiling on macos and windows with mingw
MSVC - not testing

**Comment by TheCodez** [comment]
The open api isnt't in the normal download. Its only in the [repository](http://sourceforge.net/p/optipng/mercurial/ci/default/tree/src/opnglib/). I am having problems getting that folder with subdirectories into qt. Could you also include that.

**Comment by amakaseev** [comment]
I connected [OptiPNG](http://optipng.sourceforge.net)

**Comment by TheCodez** [comment]
Yeah but I need the programmable interface from [Repository](http://sourceforge.net/p/optipng/mercurial/ci/default/tree/src/) ( the opng folder). http://optipng.sourceforge.net/doc/html/index.html

**Comment by amakaseev** [comment]
see /optipng-0.7.5/src/optipng/optipng.c
function: static int process_files(int argc, char *argv[]) for example

**Comment by TheCodez** [comment]
The opng lib is the way to go.

```
int opng_optimize_file	(	opng_optimizer_t * 	optimizer,
const char * 	in_fname,
const char * 	out_fname,
const char * 	out_dirname 
)
```

**Comment by TheCodez** [comment]
Your example is the code the command line version uses

**Comment by amakaseev** [comment]
optim.c
/*
 * Image file optimization
 */
static void
opng_optimize_impl(const char *infile_name)

**Comment by amakaseev** [comment]
optipng.c -  command line tool, isn't connected to the project
but in it it is possible to spot as to use library

**Comment by amakaseev** [comment]
include optipng.h and use this interface

**Comment by TheCodez** [comment]
You're missing zlib project

**Comment by amakaseev** [comment]
MS not include zlib? what error on compile?

**Comment by TheCodez** [comment]
optim.c line 27

**Comment by amakaseev** [comment]
ok, one moment

**Comment by TheCodez** [comment]
if you include can you also include opnglib from http://sourceforge.net/p/optipng/mercurial/ci/default/tree/src/

**Comment by amakaseev** [comment]
what for? in what a difference from original optipng?

**Comment by TheCodez** [comment]
Thats just an extra lib from optipng for integrating optipng into existung code, but it's only in the repo code.

**Comment by amakaseev** [comment]
everything is at first sight identical
look at SpriteSheetPacker/optipng

**Comment by amakaseev** [comment]
you can modify optipng.pri
if additional optipng modules are necessary

**Comment by TheCodez** [comment]
I'll do that, but do you add zlib?

**Comment by amakaseev** [comment]
yes, I connected look at optipng.pri

**Comment by amakaseev** [comment]
and I would advise to use original optipng as it is used by TexturePacker

**Comment by TheCodez** [comment]
Do you have to manually add those header and sources to the pri file?

**Comment by amakaseev** [comment]
yes of course
it is possible of course and to add the right button files to .pri but then it won't be structured

**Comment by TheCodez** [comment]
I couldn't get opng_optimize to work. I tried adding opnglib from the development repo into the pri file, but i'm getting lots of linker errrors.

**Comment by amakaseev** [comment]
i commited simple usage [OptiPNG](http://optipng.sourceforge.net)
optimization very long on time therefore it should be transferred to a separate thread and also to take out in settings opportunity optimization shutdown

**Comment by TheCodez** [comment]
Your implementation works? I did it the same just wasn't error checking yet. Maybe I wasn't waiting long enuough..

**Comment by amakaseev** [comment]
Yes it works, but very slowly if a texture is a big

**Comment by TheCodez** [comment]
Alright, I do the ui implementation then

**Comment by amakaseev** [comment]
Thanks, would be remarkable, don't forget about command-line

**Comment by amakaseev** [comment]
I now actively develop polygon sprite

**Comment by TheCodez** [comment]
How could i forget about the commandline :smile: . It was the first I implemented

**Comment by TheCodez** [comment]
Should I do a pull request with a non multithreaded version first?

**Comment by amakaseev** [comment]
no, it is better to make the first enable/disable optimization 
and enable this on command line :)

**Comment by amakaseev** [comment]
multithreaded will work only in gui version...

**Comment by TheCodez** [comment]
It's weird, no matter what optimization value i use, on my test file the reduction is always 4KB

**Comment by amakaseev** [comment]
what result is given out by the console version?
if to download exe file and run from http://optipng.sourceforge.net

**Comment by TheCodez** [comment]
Same result. Different test file gave slightly better result.  I tested it in texture packer and there the reduction is also minimal.

**Comment by amakaseev** [comment]
[ImageOptim](https://imageoptim.com) shows the best results in my tests

**Comment by amakaseev** [comment]
but it also uses optipng
https://github.com/pornel/ImageOptim

**Comment by TheCodez** [comment]
pngquant seems good you can optimize the image data by itself

**Comment by TheCodez** [comment]
ImageOptim seems to use multiple backend

**Comment by amakaseev** [comment]
I didn't study it, only used the build version

**Comment by TheCodez** [comment]
The library of pngquant is really lightweight but I got some compile errors integrating it into qt

**Comment by amakaseev** [comment]
what errors?
how better pngquant optimizes?

**Comment by TheCodez** [comment]
expected constant expression
missing includes
#include <getopt.h>
#include <unistd.h>

The webpage says up to ~70%. In my test a file went from 472kb to 142kb

**Comment by TheCodez** [comment]
ok got that compiling accidently imprted the commandline version file

**Comment by TheCodez** [comment]
I'm currently adding multithreading to image optimization. This also allows much more precise output of whats currently generated. I'm almost done the only problem i'm still having it's crashing when using multiple scaling variants.

**Comment by amakaseev** [comment]
for optimization of png there shouldn't be a difference because of the multiple scaling variants.

**Comment by amakaseev** [comment]
than I can help?

**Comment by TheCodez** [comment]
It's because it's running those thread simultaneously and optipng doens't allow multithreading.

**Comment by TheCodez** [comment]
I'll create a branch where you can take a look at my current progress

**Comment by amakaseev** [comment]
well, I think it is necessary to begin optimization of png after all other tasks are carried out and atlases are kept for different scales

**Comment by TheCodez** [comment]
Here's my working branch: https://github.com/TheCodez/sprite-sheet-packer/tree/optimize_thread

**Comment by amakaseev** [comment]
plz see http://doc.qt.io/qt-5/qtconcurrentrun.html
will use proshchy maybe this opportunity

**Comment by amakaseev** [comment]
QFuture<void> future = QtConcurrent::run(std::bind(optimizePNG, "file.png", optLevel));

**Comment by TheCodez** [comment]
This would be simpler, but it probably would need changes in the optipng source to support running more than 1 optimization at the same time.

**Comment by TheCodez** [comment]
This would be simpler, but it probably would need changes in the optipng source to support running more than 1 optimization at the same time.

**Comment by TheCodez** [comment]
I might have to take a look at the development branch which seems to support optimizing multiple files at oncel.

**Comment by TheCodez** [comment]
Could you test this branch https://github.com/TheCodez/sprite-sheet-packer/tree/optimize_opng
I'm using the development branch of optipng there and it's not working good. The file size gets even much bigger

**Comment by amakaseev** [comment]
>Do you think it's a good idea to run it using a QProcess?

if it doesn't turn out to build in source codes sprite sheet packer.
Then it is really better to start ready decisions

**Comment by TheCodez** [comment]
I'll probably see tomorrow when i'm continuing the implementation.

**Comment by TheCodez** [comment]
If done correctly I should be able to process multiple files at once. Probably need some mutex locking, because I create ONE optimizer in the Main thread and use it in the other threads e.g. opng_optimize_file(optimizer, ....)

**Comment by TheCodez** [comment]
Haven't yet managed to create a version which optimizes every file in a different thread. For now i optimize all images in the same thread.

**Comment by TheCodez** [comment]
Well never mind. After some more mutexes i got it working :+1:

**Comment by TheCodez** [comment]
Now i want to change it like this. I create as many threads as scaling variants, and every thread :
Writes PNG
Writes data file
Optimizes PNG

**Comment by amakaseev** [comment]
>Writes data file
this operation very fast...
maybe only Writes PNG and Optimizes PNG ?

**Comment by amakaseev** [comment]
the effect of optimization "optipng" completely invisible :(
can clean it up?
because now added PVR optimization
and qt save png very well

**Comment by TheCodez** [comment]
I would keep it, although it's optimization are minimal.

**Comment by amakaseev** [comment]
If you plan to Use them then let it stay. But in this case cann't do everything as planned in one thread, so as not to waste time on the progress bar ?

**Comment by TheCodez** [comment]
on  which platforms are pvr images supported?

**Comment by amakaseev** [comment]
pvr - ios
pvr+etc1 - ios/android
http://www.cocos2d-x.org/wiki/Texture_Formats_Supported_by_Cocos2d-x

**Comment by TheCodez** [comment]
I'm currently working on the progressbar again, and i think the progress bar looks quite huge and unnecessary. I think a small progress indicator would look much better. For example this one : https://github.com/mojocorp/QProgressIndicator

What do you think?

**Comment by amakaseev** [comment]
Yes, its a good indicator :+1:

**Comment by TheCodez** [comment]
Ok I'll use that indicator then. Itry to use it for displaying most tasks e.g packing, opening project, publishing.

**Comment by amakaseev** [comment]
that's wonderful 
texturepacker does also :)

**Comment by TheCodez** [comment]
in polypack2d.h it's best to add something like the following then i can the current placing status: 
```cpp
void placeWithCallback(const ContentList<T>& inputContent, int sizeLimit = 8192, int step = 5, std::function<void (const std::string&, int, int)> callback)
```
